GRADLE_LINK=gradle
GRADLE_VER=2.2.1
GRADLE_DIR=gradle-$GRADLE_VER
GRADLE_INSTALADOR=$GRADLE_DIR-all.zip
GRADLE_INSTALADOR_URL_COMPLETA=https://services.gradle.org/distributions/$GRADLE_INSTALADOR
export GRADLE_HOME=$FERRAMENTAS_DIR/gradle
export PATH=$GRADLE_HOME/bin:$PATH
