#!/bin/bash

JBOSS_EAP_LINK=jboss-eap
JBOSS_EAP_VER=${JBOSS_EAP_VER:-6.4} # versões suportadas: 6.4
JBOSS_EAP_INSTALA_DIR=${JBOSS_EAP_INSTALA_DIR:-$FUNCOES_DIR/instalar}
JBOSS_EAP_DIR=$JBOSS_EAP_LINK-$JBOSS_EAP_VER
JBOSS_EAP_INSTALADOR=$JBOSS_EAP_DIR.0.zip
JBOSS_EAP_INSTALA_OPCS='--nao-baixa-arquivo'

case $PLATAFORMA in
    Cygwin) 
        export JBOSS_EAP_HOME=`cygpath -m "$FERRAMENTAS_DIR"/$JBOSS_EAP_DIR`
        [[ $JBOSS = $JBOSS_EAP_LINK ]] && export PATH=$FERRAMENTAS_DIR/$JBOSS_EAP_DIR/bin:$PATH
        ;;
    *) 
        export JBOSS_EAP_HOME=$FERRAMENTAS_DIR/$JBOSS_EAP_LINK
        [[ $JBOSS = $JBOSS_EAP_LINK ]] && export PATH=$JBOSS_EAP_HOME/bin:$PATH
        ;;
esac

JBOSS_EAP_BASE=$JBOSS_EAP_HOME/standalone
JBOSS_EAP_CONFIGURATION=$JBOSS_EAP_BASE/configuration
JBOSS_EAP_DEPLOYMENTS=$JBOSS_EAP_BASE/deployments
JBOSS_EAP_LOG=$JBOSS_EAP_BASE/log

[[ $JBOSS = $JBOSS_EAP_LINK ]] && export JBOSS_HOME=$JBOSS_EAP_HOME || true

# vim set ts=4, sw=4, expandtab:
